# D:/git-repos/rainmeter-plugins/rainmeter-python-plugin/mcppt-toolchain.cmake
# Project toolchain file generated by MCPPT. 
#
# The lines ending with the comments `#-global-toolchain`, `#-global-include`, `#-local-toolchain`, and `#-local-include` include the toolchains
# for the global and local copies of vcpkg. If MCPPT needs to update where these files are located, these 
# comments are used to locate these include statements in the file.
#
# Don't remove these comments or add anything after them, or else MCPPT will not detect the comments. 
# If the comments are not detected, these include lines be added (commented out) to the top of the file.
#
# Additionally, don't include anything else on these lines, otherwise MCPPT may remove your changes. 
# You may, however comment one of the lines out to disable that toolchain. MCPPT will watch for this and
# preserve that commented state if it needs to changes the paths.
#
# Otherwise, you may edit these file however you wish.
# =======================================================================================================

# Global toolchain is disabled by default:
# include("D:/tools/mcppt/vcpkg/scripts/buildsystems/vcpkg.cmake") #-global-toolchain
# set(GLOBAL_TRIPLET_INCLUDE_DIR D:/tools/mcppt/vcpkg/installed/${VCPKG_TARGET_TRIPLET}/include) #-global-include
# include_directories(${GLOBAL_TRIPLET_INCLUDE_DIR})

# Local toolchain:
include("D:/tools/mcppt/vcpkg/scripts/buildsystems/vcpkg.cmake") #-local-toolchain
set(LOCAL_TRIPLET_INCLUDE_DIR D:/tools/mcppt/vcpkg/installed/${VCPKG_TARGET_TRIPLET}/include) #-local-include
include_directories(${LOCAL_TRIPLET_INCLUDE_DIR})

# Boost - Prebuilt:
set(RAINMETER_API_ROOT "D:/libraries/common/rainmeter-plugin-sdk/API/")
set(RAINMETER_API_LIB "D:/libraries/common/rainmeter-plugin-sdk/API/x64/Rainmeter.lib")
