# D:/git-repos/rainmeter-plugins/rainmeter-python-plugin/mct_user_toolchain.cmake
# Project toolchain file generated by MCT. 
# DO NOT EDIT! ALL CHANGES WILL BE OVERRIDDEN!
# =======================================================================================================

# Local toolchain:
include(D:/tools/mct/vcpkg/scripts/buildsystems/vcpkg.cmake) #-local-toolchain
set(LOCAL_TRIPLET_INCLUDE_DIR D:/tools/mct/vcpkg/installed/${VCPKG_TARGET_TRIPLET}/include) #-local-include
include_directories(${LOCAL_TRIPLET_INCLUDE_DIR})

# User Toolchain Values:
set(RAINMETER_API_ROOT D:/libraries/common/rainmeter-plugin-sdk/API/)
set(RAINMETER_API_LIB D:/libraries/common/rainmeter-plugin-sdk/API/x64/Rainmeter.lib)

# Project Shared Includes:
